# Generated by Django 5.0.6 on 2024-06-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebean', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
